# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [ ]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [ ]:
np.shape(x)

(40,)

5. Print the type of the previous array in question 3

In [ ]:
x.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [ ]:
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [ ]:
x.ndim

1

8. Create a boolean array with all the True values

In [ ]:
True_values = (x>0)
True_values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [4]:
y = np.arange(20).reshape(4,5)
print(y)
y.ndim

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


2

10. Create a three dimensional array



In [8]:
y = np.arange(27).reshape(3,3,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [7]:
np.flip(y)

array([[[26, 25, 24],
        [23, 22, 21],
        [20, 19, 18]],

       [[17, 16, 15],
        [14, 13, 12],
        [11, 10,  9]],

       [[ 8,  7,  6],
        [ 5,  4,  3],
        [ 2,  1,  0]]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
z = np.zeros(10)
print(z)
z[4] = 1
print(z) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [10]:
arr = np.array([1, 2, 3, 4, 5]) 
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
array = (arr1>arr2)
array

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [ ]:
arr = np.arange(9)
odd_arr = arr[arr%2 != 0]
odd_arr

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [ ]:
arr[arr%2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)
np.put(arr, [5, 6, 7], [8,10, 12])
arr

array([ 0,  1,  2,  3,  4,  8, 10, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
arr = np.ones((5,5))
arr
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d[1,-2] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  
                   [[7, 8, 9],
                    [10, 11, 12]]])
arr3d[0,0] = 64
arr3d


array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
arr = np.array([[ 1,  2,  3],
                [ 4,  5,  6],
                [ 7,  8,  9]])
arr[0:1]

array([[1, 2, 3]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
arr = np.array([[ 1,  2,  3],
                [ 4,  5,  6],
                [ 7,  8,  9]])
arr[1:2, 1:2]

array([[5]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
arr = np.array([[ 1,  2,  3],
                [ 4,  5,  6],
                [ 7,  8,  9]])
arr[:2, -1]

array([3, 6])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
tenbyten = np.random.rand(10,10)*10
tenbyten = tenbyten.astype(np.int)
print(tenbyten)
print(tenbyten.min())
print(tenbyten.max())

[[0.88270897 0.81377535 0.93428773 0.63743862 0.64374566 0.98227216
  0.41854843 0.23075533 0.20452323 0.49112565]
 [0.7618714  0.2146083  0.50283639 0.22096642 0.32889331 0.66546054
  0.9304121  0.9604145  0.05381254 0.02312963]
 [0.87692342 0.5715093  0.74183112 0.46154822 0.45177061 0.99462118
  0.2678483  0.7230203  0.54334152 0.25144342]
 [0.18245768 0.62247178 0.05098295 0.30500437 0.68485855 0.8550841
  0.64894091 0.01219123 0.408369   0.1808719 ]
 [0.18066876 0.00605425 0.98358246 0.46613881 0.95166994 0.74844309
  0.72086417 0.11223808 0.45588832 0.08608523]
 [0.328427   0.54334891 0.07734359 0.9290117  0.81832865 0.1660457
  0.35182176 0.98254741 0.78192804 0.28465646]
 [0.19806648 0.21942487 0.6156832  0.8248799  0.1436961  0.00224598
  0.00740019 0.53908491 0.49959456 0.20918241]
 [0.49764332 0.11775644 0.05711771 0.98750196 0.8018041  0.40599867
  0.09561804 0.41479862 0.98476983 0.27639814]
 [0.58043365 0.29829408 0.02965475 0.56324949 0.08011577 0.53919114
  0.45718757 0

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a, b))[0]

array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[names != "Will"])

[[-0.57395979 -1.11857017 -1.14044117 -0.94536126]
 [-0.15795819 -1.25477587 -1.54067382  0.48647293]
 [ 0.94942004  1.46064645  0.04808791 -0.44942913]
 [ 0.86966837  0.13657585  0.44597971  0.37190827]
 [ 1.39870196 -0.49873079  0.19826796  0.13134049]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

data[names=="Bob"] 

array([[ 1.45370658, -0.1039462 , -1.07309308, -0.05238025],
       [-0.90518323,  0.18450549,  1.16012525, -0.50645688]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
arr = np.arange(1, 16)
arr = arr.reshape(5,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
arr = np.arange(1, 17)
arr = arr.reshape(2, 2, 4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [ ]:
arr = np.swapaxes(arr,0,2)
arr

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [13]:
y = np.random.rand(10)
z = np.sqrt(y)
print(z)
np.where(z<0.5, 0, z)

[0.78449372 0.69741378 0.71766791 0.86991371 0.95996902 0.42091269
 0.9303177  0.80873896 0.67404363 0.86049132]


array([0.78449372, 0.69741378, 0.71766791, 0.86991371, 0.95996902,
       0.        , 0.9303177 , 0.80873896, 0.67404363, 0.86049132])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
x = np.random.rand(12)
y = np.random.rand(12)

z = np.maximum(x, y)
print(z)

[0.50021824 0.51397227 0.91727017 0.56812108 0.66279079 0.44245229
 0.61591602 0.47881123 0.67382576 0.46528722 0.57394795 0.86820209]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
newColumn.shape = (3, 1)

sampleArray = np.delete(sampleArray, 1, 1)
sampleArray = np.hstack((sampleArray[:,:1], newColumn, sampleArray[:,1:]))
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y, out = None)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [15]:
x = np.random.rand(20)
print(x)
print(np.cumsum(x))

[0.8509572  0.90412678 0.77508281 0.03475663 0.32631415 0.03872501
 0.85320174 0.92637796 0.91053861 0.36852871 0.17719623 0.54387065
 0.58562911 0.42560147 0.28376719 0.7392943  0.4918553  0.01227775
 0.44491809 0.2515149 ]
[0.8509572  1.75508397 2.53016678 2.56492341 2.89123757 2.92996257
 3.78316431 4.70954227 5.62008088 5.98860959 6.16580582 6.70967647
 7.29530557 7.72090705 8.00467424 8.74396853 9.23582384 9.24810158
 9.69301967 9.94453458]
