# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [28]:
x = np.array([1, 2, 3, 5])
y = np.array([6, 7, 8, 9])

z = np.vstack((x, y))
print(z)

[[1 2 3 5]
 [6 7 8 9]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [26]:
x = np.array([1, 2, 3, 5])
y = np.array([6, 7, 8, 9])

z = np.hstack((x, y))
print(z)

[1 2 3 5 6 7 8 9]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [37]:
print(z)
z.flat[1]

[[1 2 3 5]
 [6 7 8 9]]


2

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [39]:
print(z)
z.flat[:]

[[1 2 3 5]
 [6 7 8 9]]


array([1, 2, 3, 5, 6, 7, 8, 9])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [41]:
x = z.flat[:]
print(x)

x = x.reshape(2, 4)
print(x)

[1 2 3 5 6 7 8 9]
[[1 2 3 5]
 [6 7 8 9]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [55]:
x = np.random.rand(5,5)*10
x = x.astype(np.int32)
print(x)

print(np.sqrt(x))

[[8 3 8 9 6]
 [8 4 7 4 8]
 [7 5 0 6 4]
 [9 9 2 0 8]
 [2 6 0 5 7]]
[[2.82842712 1.73205081 2.82842712 3.         2.44948974]
 [2.82842712 2.         2.64575131 2.         2.82842712]
 [2.64575131 2.23606798 0.         2.44948974 2.        ]
 [3.         3.         1.41421356 0.         2.82842712]
 [1.41421356 2.44948974 0.         2.23606798 2.64575131]]


## Question:8

### Create 5x6 an array and find the mean?

In [58]:
x = np.random.rand(5,6)*10
x = x.astype(np.int32)
print(x)
np.mean(x)

[[5 6 6 2 2 6]
 [7 9 7 6 0 7]
 [7 2 2 2 7 2]
 [0 5 3 5 2 5]
 [5 3 9 7 2 3]]


4.466666666666667

## Question:9

### Find the standard deviation of the previous array in Q8?

In [59]:
np.std(x)

2.486407493196202

## Question:10

### Find the median of the previous array in Q8?

In [60]:
np.median(x)

5.0

## Question:11

### Find the transpose of the previous array in Q8?

In [61]:
x.T

array([[5, 7, 7, 0, 5],
       [6, 9, 2, 5, 3],
       [6, 7, 2, 3, 9],
       [2, 6, 2, 5, 7],
       [2, 0, 7, 2, 2],
       [6, 7, 2, 5, 3]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [67]:
x = np.random.rand(4, 4)*10
x = x.astype("int32")
print(x)
np.trace(x)

[[4 0 0 5]
 [7 8 8 7]
 [7 7 0 4]
 [2 8 4 9]]


21

## Question:13

### Find the determinant of the previous array in Q12?

In [68]:
np.linalg.det(x)

-2260.0000000000014

## Question:14

### Find the 5th and 95th percentile of an array?

In [69]:
print(np.percentile(x, 5))
print(np.percentile(x, 95))


0.0
8.25


## Question:15

### How to find if a given array has any null values?

In [83]:
a = np.array([np.nan, 1, 2, 3, 4, 5, 6, 8])
np.isnan(a).any()

True