# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
a = np.array([1, 2, 4])
b = np.array([2, 4, 5])
x = np.vstack((a,b))
print(x)

[[1 2 4]
 [2 4 5]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
a = np.array([1, 2, 4])
b = np.array([2, 4, 5])
print(np.hstack((a,b)))

[1 2 4 2 4 5]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
print(x.flatten())

[1 2 4 2 4 5]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:
print(x.flatten())

[1 2 4 2 4 5]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
y = x.flatten()
z = y.reshape(2,3)


array([[1, 2, 4],
       [2, 4, 5]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [17]:
z = np.random.rand(25)
z = z.reshape(5,5)
print(np.sqrt(z))

[[0.99073665 0.55741976 0.77355171 0.80949798 0.89350015]
 [0.49883799 0.43529061 0.92253031 0.79927287 0.80946772]
 [0.37586233 0.74274424 0.80974739 0.98227669 0.99325652]
 [0.49477504 0.89323932 0.63686846 0.18889481 0.58936017]
 [0.1636576  0.56059359 0.36280458 0.31349452 0.91755885]]


## Question:8

### Create 5x6 an array and find the mean?

In [20]:
z = np.random.rand(30)
z = z.reshape(5, 6)
print(np.mean(z))

0.4129889002283571


## Question:9

### Find the standard deviation of the previous array in Q8?

In [21]:
print(np.std(z))

0.2847888462134029


## Question:10

### Find the median of the previous array in Q8?

In [22]:
print(np.median(z))

0.411211312555606


## Question:11

### Find the transpose of the previous array in Q8?

In [23]:
z.T

array([[0.80951009, 0.20419382, 0.41789713, 0.11765681, 0.56958027],
       [0.87262024, 0.68512785, 0.6558128 , 0.57553409, 0.31087478],
       [0.02037015, 0.74003394, 0.42638644, 0.50492796, 0.74989763],
       [0.12593537, 0.265443  , 0.85499467, 0.18872005, 0.01995017],
       [0.21335594, 0.71659619, 0.82539085, 0.5354464 , 0.03220118],
       [0.36117002, 0.16852762, 0.00739038, 0.40452549, 0.00959565]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [43]:
a = np.array([[9, 2, 3, 0], [6, 2, 7, 8], [4, 7, 9, 9], [4, 8, 0, 7]])
print(sum(a.diagonal()))

27


## Question:13

### Find the determinant of the previous array in Q12?

In [47]:
print(np.linalg.det(a))

-3162.999999999998


## Question:14

### Find the 5th and 95th percentile of an array?

In [48]:
print(np.percentile(a, 5))
print(np.percentile(a, 95))

0.0
9.0


## Question:15

### How to find if a given array has any null values?

In [51]:
print(np.isnan(a))
print(np.isnan(a).any())

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
False
