# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [9]:
#type your code here
import numpy as np
from numpy import genfromtxt

2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [10]:
#type your code here
ingrdnts = np.array(['milk', 'sugar','eggs', 'flour','butter'])
print(ingrdnts)


['milk' 'sugar' 'eggs' 'flour' 'butter']


3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [11]:
#type your code here
recipes = genfromtxt('recipes.csv', delimiter=',')
print(recipes)
Cupcakes = recipes[0]
print(Cupcakes)

[[2.    0.75  2.    1.    0.5  ]
 [1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]
 [4.    0.5   2.    2.    0.5  ]]
[2.   0.75 2.   1.   0.5 ]


4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [12]:
#type your code here
menu = np.array(['Cupcakes', 'Pancake', 'Cookie', 'Bread'])
menu = menu.reshape(4,1)
menu_card = np.hstack((menu, recipes))
for b in menu_card:
    for a in b:
        print(a, end = " cups ")
    print("\n")



Cupcakes cups 2.0 cups 0.75 cups 2.0 cups 1.0 cups 0.5 cups 

Pancake cups 1.0 cups 0.125 cups 1.0 cups 1.0 cups 0.125 cups 

Cookie cups 2.75 cups 1.5 cups 1.0 cups 0.0 cups 1.0 cups 

Bread cups 4.0 cups 0.5 cups 2.0 cups 2.0 cups 0.5 cups 



5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [13]:
#type your code here
eggs = recipes[:,2]
print(eggs)

[2. 1. 1. 2.]


6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [14]:
#type your code here
print(eggs == 1)
one_egg_dishes = recipes[recipes[:,2] == 1]
print(one_egg_dishes)

[False  True  True False]
[[1.    0.125 1.    1.    0.125]
 [2.75  1.5   1.    0.    1.   ]]


7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [15]:
#type your code here

Cookies = recipes[2]
print(Cookies)

[2.75 1.5  1.   0.   1.  ]


8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [16]:
#type your code here
double_batch = Cupcakes * 2
print(double_batch)

[4.  1.5 4.  2.  1. ]


9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [17]:
#type your code here
grocery_list = Cookies + double_batch
print(grocery_list)

[6.75 3.   5.   2.   2.  ]


In [18]:
x = np.stack((ingrdnts, grocery_list))
print(x)

[['milk' 'sugar' 'eggs' 'flour' 'butter']
 ['6.75' '3.0' '5.0' '2.0' '2.0']]
